on:
  push:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest
    name: Test building HTML of IFE model
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Test building the image and exporting HTML
      uses: ./