on:
  push:
    branches:
      - '*'
# All branches that are not slashed! (such as release/...)

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build container and test
    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Image
      uses: docker/build-push-action@v4
      with:
        push: false
        load: true
        tags: mtreber/capella-html-exporter:latest

    - name: Checkout
      uses: actions/checkout@v3

#    - name: Test by manually invoking docker
#      run: |
#        docker run --rm -v `pwd`/model:/workdir mtreber/capella-html-exporter:latest capella-automations
#        pwd
#        ls -l

    - name: Test using the action
      uses: ./
      with:
        model-name: capella-automations
        path-model-folder: model/capella-automations
        entrypoint: model/entrypoint.sh

    - name: Archive HTML export and validation report
      uses: actions/upload-artifact@v4
      with:
        name: validation-report-html-export
        path: artifacts
