on:
  push:
    branches:
      - '*'

jobs:
  build_test:
    runs-on: ubuntu-latest
    name: Test building HTML of IFE model
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Test building the image and exporting HTML
      uses: ./
    - 
      name: Archive HTML export and validation report
      uses: actions/upload-artifact@v3
      with:
        name: validation-report-html-export
        path: artifacts